[profile.release]
panic = 'unwind'
[workspace]
members = [
    "cli",
    "executor",
    "inspect",
    "rpc",
    "rpc-client",
    "common/constants",
    "common/pallets/*",
    "common/primitives",
    "common/traits",

]
